name: Build and Deliver

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Create package
        run: |
          mkdir package
          cp app.py package/
          cp test_app.py package/
          cp requirements.txt package/
          cp README.md package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-cicd-package
          path: package/